python current_strip_epu_solver.py \
--kick /Users/johan/git/tracy-3.5_dev/projects/in/lattice/NSLS-II/eu49_2m_heli.txt \
--beam-energy 430e6 \
--units 'Tˆ2m^2' \
--kick-scale 1.0 \
--strip-layout horizontal \
--x-range 20e-3 \
--horizontal-strips-per-plane 11 \
--gap 15e-3 \
--horizontal-weight 1.0 \
--y-range 5e-3 \
--vertical-weight 0.0 \
--limit 50.0 \
--target-mode nonlinear \
--max-fit-relative-rms 0.98 \
--min-full-map-rms-reduction-factor 0.97 \
--out-prefix claris_und_fixed \
--show
