PYTHONPATH=.. python3 -m apple2.cli \
  --period 56 \
  --periods 17 \
  --gap 21 \
  --width 40 \
  --height 40 \
  --remanence 1.25 \
  --motion elliptical \
  --phase-mm 0 \
  --end-block-fraction 0.5 \
  --end-magnetization-fraction 0.5 \
  --end-clearance-mm 0 \
  --samples 2401 \
  --central-periods 12 \
  --harmonics 1 3 5 \
  --min-total-amplitude 1e-4 \
  --max-relative-residual 0.10 \
  --csv runs/phase_0/field.csv \
  --json runs/phase_0/analysis.json
